# Generated by Django 4.0.6 on 2022-07-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('account_Type', models.CharField(choices=[('student', 'STUDENT'), ('tutor', 'TUTOR')], default='none', max_length=100)),
                ('github', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('linkedinn', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
