# Generated by Django 4.0.6 on 2022-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_account_type_alter_profile_linkedinn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_Type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('tutor', 'TUTOR')], default='none', max_length=100),
        ),
    ]
