# Generated by Django 4.0.6 on 2022-07-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedinn',
            new_name='linkedin',
        ),
    ]
