# Generated by Django 4.0.6 on 2022-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_Type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('tutor', 'TUTOR')], default='none', max_length=10),
        ),
    ]
