# Generated by Django 4.0.6 on 2022-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_facebook_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
